### ISSUE TITLE
Broken panel, or timing issue?

### ISSUE THREAD

**Issue by cyclotron3k** [mcer12/Inkster-ESP32#2]
Quick question: does this look like a broken panel, or a timing issue? (Or both?!).

It's a ED097OC1(LF) pulled from a Kindle DX. I also tried the demo code from the EPDiy project and that had the same issues.

![PXL_20220524_011107502](https://user-images.githubusercontent.com/3222878/169929168-7700abbb-19a5-463f-9522-357e49f0f15b.jpg)

Thanks for any help!

**Comment by mcer12** [comment]
There’s some compatibility issues with epdiy & OC1 but afaik it’s subtle,
just some pixel shift - this has been discussed on epdiy github as well as
epdiy slack channel so check that out. But this definitely looks like
typical mechanical damage - smashed display in the middle, sorry.

út 24. 5. 2022 v 3:21 odesílatel cyclotron3k ***@***.***>
napsal:

**Comment by cyclotron3k** [comment]
Ok, thanks for the advice! I'll try a new panel...
